In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,5,6])

In [13]:
type(a)

numpy.ndarray

In [14]:
a

array([1, 2, 3, 4, 5, 6])

In [15]:
2*a

array([ 2,  4,  6,  8, 10, 12])

In [16]:
data = np.random.randn(3,4)

In [17]:
data

array([[ 0.89833107, -1.32121558, -1.97442536,  1.40550359],
       [ 1.05660262, -0.5167885 ,  0.19589142,  0.12225214],
       [-1.22458762, -1.10891641,  0.26461727,  2.32517956]])

In [18]:
data1 = np.arange(10)

In [19]:
data1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
data1.ndim

1

In [21]:
data.shape

(3, 4)

In [22]:
 b = np.array([[100]])

In [24]:
b.ndim

2

In [25]:
b.shape

(1, 1)